version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testDockerEC2
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volume/postgres/pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DATABASE: testDockerEC2
      #DB_SOURCE: postgres://postgres:root@db:5432/testDockerEC2
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    driver: bridge
